appname = property_listing_api
httpport = 8080
runmode = dev
location_service_url = http://192.168.0.35:8099/api
property_service_url = http://192.168.0.35:8099/api
api_key = ${API_KEY}
http_client_timeout_seconds = 10
